const initialCards = [
	{
		name: 'Two of spades',
		suite: 'spades',
		value: 2,
		image: '/cards_images/2_of_hearts.png',
		symbol: '♠',
	},
	{
		name: 'Two of hearts',
		suite: 'hearts',
		value: 2,
		image: '/cards_images/2_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Two of clubs',
		suite: 'clubs',
		value: 2,
		image: '/cards_images/2_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Two of diamonds',
		suite: 'diamonds',
		value: 2,
		image: '/cards_images/2_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Three of spades',
		suite: 'spades',
		value: 3,
		image: '/cards_images/3_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Three of hearts',
		suite: 'hearts',
		value: 3,
		image: '/cards_images/3_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Three of clubs',
		suite: 'clubs',
		value: 3,
		image: '/cards_images/3_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Three of diamonds',
		suite: 'diamonds',
		value: 3,
		image: '/cards_images/3_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Four of spades',
		suite: 'spades',
		value: 4,
		image: '/cards_images/4_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Four of hearts',
		suite: 'hearts',
		value: 4,
		image: '/cards_images/4_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Four of clubs',
		suite: 'clubs',
		value: 4,
		image: '/cards_images/4_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Four of diamonds',
		suite: 'diamonds',
		value: 4,
		image: '/cards_images/4_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Five of spades',
		suite: 'spades',
		value: 5,
		image: '/cards_images/5_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Five of hearts',
		suite: 'hearts',
		value: 5,
		image: '/cards_images/5_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Five of clubs',
		suite: 'clubs',
		value: 5,
		image: '/cards_images/5_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Five of diamonds',
		suite: 'diamonds',
		value: 5,
		image: '/cards_images/5_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Six of spades',
		suite: 'spades',
		value: 6,
		image: '/cards_images/6_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Six of hearts',
		suite: 'hearts',
		value: 6,
		image: '/cards_images/6_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Six of clubs',
		suite: 'clubs',
		value: 6,
		image: '/cards_images/6_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Six of diamonds',
		suite: 'diamonds',
		value: 6,
		image: '/cards_images/6_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Seven of spades',
		suite: 'spades',
		value: 7,
		image: '/cards_images/7_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Seven of hearts',
		suite: 'hearts',
		value: 7,
		image: '/cards_images/7_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Seven of clubs',
		suite: 'clubs',
		value: 7,
		image: '/cards_images/7_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Seven of diamonds',
		suite: 'diamonds',
		value: 7,
		image: '/cards_images/7_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Eight of spades',
		suite: 'spades',
		value: 8,
		image: '/cards_images/8_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Eight of hearts',
		suite: 'hearts',
		value: 8,
		image: '/cards_images/8_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Eight of clubs',
		suite: 'clubs',
		value: 8,
		image: '/cards_images/8_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Eight of diamonds',
		suite: 'diamonds',
		value: 8,
		image: '/cards_images/8_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Nine of spades',
		suite: 'spades',
		value: 9,
		image: '/cards_images/9_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Nine of hearts',
		suite: 'hearts',
		value: 9,
		image: '/cards_images/9_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Nine of clubs',
		suite: 'clubs',
		value: 9,
		image: '/cards_images/9_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Nine of diamonds',
		suite: 'diamonds',
		value: 9,
		image: '/cards_images/9_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Ten of spades',
		suite: 'spades',
		value: 10,
		image: '/cards_images/10_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Ten of hearts',
		suite: 'hearts',
		value: 10,
		image: '/cards_images/10_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Ten of clubs',
		suite: 'clubs',
		value: 10,
		image: '/cards_images/10_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Ten of diamonds',
		suite: 'diamonds',
		value: 10,
		image: '/cards_images/10_of_diamonds.png',
		symbol: '♦',
	},

	{
		name: 'Jack of spades',
		suite: 'spades',
		value: 10,
		image: '/cards_images/jack_of_spades2.png',
		symbol: '♠',
	},
	{
		name: 'Jack of hearts',
		suite: 'hearts',
		value: 10,
		image: '/cards_images/jack_of_hearts2.png',
		symbol: '♥',
	},
	{
		name: 'Jack of clubs',
		suite: 'clubs',
		value: 10,
		image: '/cards_images/jack_of_clubs2.png',
		symbol: '♣',
	},
	{
		name: 'Jack of diamonds',
		suite: 'diamonds',
		value: 10,
		image: '/cards_images/jack_of_diamonds2.png',
		symbol: '♦',
	},

	{
		name: 'Queen of spades',
		suite: 'spades',
		value: 10,
		image: '/cards_images/queen_of_spades2.png',
		symbol: '♠',
	},
	{
		name: 'Queen of hearts',
		suite: 'hearts',
		value: 10,
		image: '/cards_images/queen_of_hearts2.png',
		symbol: '♥',
	},
	{
		name: 'Queen of clubs',
		suite: 'clubs',
		value: 10,
		image: '/cards_images/queen_of_clubs2.png',
		symbol: '♣',
	},
	{
		name: 'Queen of diamonds',
		suite: 'diamonds',
		value: 10,
		image: '/cards_images/queen_of_diamonds2.png',
		symbol: '♦',
	},

	{
		name: 'King of spades',
		suite: 'spades',
		value: 10,
		image: '/cards_images/king_of_spades2.png',
		symbol: '♠',
	},
	{
		name: 'King of hearts',
		suite: 'hearts',
		value: 10,
		image: '/cards_images/king_of_hearts2.png',
		symbol: '♥',
	},
	{
		name: 'King of clubs',
		suite: 'clubs',
		value: 10,
		image: '/cards_images/king_of_clubs2.png',
		symbol: '♣',
	},
	{
		name: 'King of diamonds',
		suite: 'diamonds',
		value: 10,
		image: '/cards_images/king_of_diamonds2.png',
		symbol: '♦',
	},

	{
		name: 'Ace of spades',
		suite: 'spades',
		value: 11,
		image: '/cards_images/ace_of_spades.png',
		symbol: '♠',
	},
	{
		name: 'Ace of hearts',
		suite: 'hearts',
		value: 11,
		image: '/cards_images/ace_of_hearts.png',
		symbol: '♥',
	},
	{
		name: 'Ace of clubs',
		suite: 'clubs',
		value: 11,
		image: '/cards_images/ace_of_clubs.png',
		symbol: '♣',
	},
	{
		name: 'Ace of diamonds',
		suite: 'diamonds',
		value: 11,
		image: '/cards_images/ace_of_diamonds.png',
		symbol: '♦',
	},
];

export default initialCards;
